### ISSUE TITLE
Refactor code

### ISSUE THREAD

**Issue by AnshDubey1999** [UAlbertaALTLab/mobidict-android#68]
This code needs a fair bit of work for code refactoring - including shared components, best coding practices, and around 50%-70% lesser code smells. I would only start this once it's a go from @aarppe @nienna73.  I do think it's worth for the future code maintenance though.
Feel free to jot down any thoughts! Expect this to take 12 hours of work just for heads up.

**Comment by nienna73** [comment]
I think this is a great idea. Cleaner code is much easier to maintain and the sooner you clean it up the easier it will be. This will delay the release of the app by a few days though. @aarppe do you have any thoughts on the matter?

**Comment by AnshDubey1999** [comment]
Most of the refactoring needed is done. Camel case renaming will be kept a work in progress.
